#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_Towns_Kanto
#define MAP_TEMPLATE        (0 | (0 << 8))
#define MAP_TESTINGMAP      (1 | (0 << 8))
#define MAP_PALLET_TOWN     (2 | (0 << 8))
#define MAP_VIRIDIAN_CITY   (3 | (0 << 8))
#define MAP_PEWTER_CITY     (4 | (0 << 8))
#define MAP_MT_MOON         (5 | (0 << 8))
#define MAP_CERULEAN_CITY   (6 | (0 << 8))
#define MAP_POWER_PLANT     (7 | (0 << 8))
#define MAP_SAFFRON_CITY    (8 | (0 << 8))
#define MAP_VERMILLION_CITY (9 | (0 << 8))
#define MAP_LAVENDER_TOWN   (10 | (0 << 8))
#define MAP_CELADON_CITY    (11 | (0 << 8))
#define MAP_FUCHSIA_CITY    (12 | (0 << 8))
#define MAP_CINNABAR_ISLAND (13 | (0 << 8))
#define MAP_CINN            (14 | (0 << 8))

// gMapGroup_Routes_Kanto
#define MAP_ROUTE22      (0 | (1 << 8))
#define MAP_ROUTE1       (1 | (1 << 8))
#define MAP_ROUTE2       (2 | (1 << 8))
#define MAP_ROUTE3       (3 | (1 << 8))
#define MAP_ROUTE4       (4 | (1 << 8))
#define MAP_ROUTE5       (5 | (1 << 8))
#define MAP_ROUTE6       (6 | (1 << 8))
#define MAP_ROUTE7       (7 | (1 << 8))
#define MAP_ROUTE8       (8 | (1 << 8))
#define MAP_ROUTE9       (9 | (1 << 8))
#define MAP_ROUTE9NORTH  (10 | (1 << 8))
#define MAP_ROUTE10      (11 | (1 << 8))
#define MAP_ROUTE10SOUTH (12 | (1 << 8))
#define MAP_ROUTE11      (13 | (1 << 8))
#define MAP_ROUTE12      (14 | (1 << 8))
#define MAP_ROUTE13      (15 | (1 << 8))
#define MAP_ROUTE14      (16 | (1 << 8))
#define MAP_ROUTE15      (17 | (1 << 8))
#define MAP_ROUTE16      (18 | (1 << 8))
#define MAP_ROUTE18      (19 | (1 << 8))
#define MAP_ROUTE24      (20 | (1 << 8))
#define MAP_ROUTE25      (21 | (1 << 8))
#define MAP_ROUTE19      (22 | (1 << 8))
#define MAP_ROUTE20      (23 | (1 << 8))
#define MAP_ROUTE17      (24 | (1 << 8))

// gMapGroup_Kanto_Gyms
#define MAP_TESTGYM        (0 | (2 << 8))
#define MAP_ELITE4TEST     (1 | (2 << 8))
#define MAP_VIRIDIAN_GYM   (2 | (2 << 8))
#define MAP_PEWTER_GYM     (3 | (2 << 8))
#define MAP_CERULEAN_GYM   (4 | (2 << 8))
#define MAP_VERMILLION_GYM (5 | (2 << 8))
#define MAP_CELADON_GYM    (6 | (2 << 8))
#define MAP_FUCHSIA_GYM    (7 | (2 << 8))
#define MAP_SAFFRON_GYM    (8 | (2 << 8))
#define MAP_CINNABAR_GYM   (9 | (2 << 8))

// gMapGroup_GymLeader_PersonalQuarters

// gMapGroup_Indoor_Pokemon_League
#define MAP_POKEMON_LEAGUE_HQ             (0 | (4 << 8))
#define MAP_STARTMAP                      (1 | (4 << 8))
#define MAP_POKEMON_LEAGUE_HQPOKECENTER   (2 | (4 << 8))
#define MAP_POKEMON_LEAGUE_RECEPTION_GATE (3 | (4 << 8))
#define MAP_POKEMON_LEAGUE_HQLAB          (4 | (4 << 8))
#define MAP_VICTORY_ROAD_F1               (5 | (4 << 8))
#define MAP_VICTORY_ROAD_F2               (6 | (4 << 8))
#define MAP_VICTORY_ROAD_F3               (7 | (4 << 8))
#define MAP_INDIGO                        (8 | (4 << 8))
#define MAP_POKEMON_LEAGUE_HQHEAD_OFFICE  (9 | (4 << 8))

// gMapGroup_Indoor_Pallet_Town
#define MAP_REDS_HOUSE       (0 | (5 << 8))
#define MAP_BLUES_HOUSE      (1 | (5 << 8))
#define MAP_PALLET_DAYCARE   (2 | (5 << 8))
#define MAP_OAKSLAB          (3 | (5 << 8))
#define MAP_POKESUPERCENTER  (4 | (5 << 8))
#define MAP_POKESUPERCENTER2 (5 | (5 << 8))
#define MAP_PALLETTOWNHOUSE1 (6 | (5 << 8))

// gMapGroup_Indoor_Viridian_City
#define MAP_VIRIDIAN_POKEMON_CENTER_F1 (0 | (6 << 8))
#define MAP_VIRIDIAN_POKE_MART         (1 | (6 << 8))
#define MAP_VIRIDIAN_FOREST            (2 | (6 << 8))
#define MAP_VIRIDIAN_CITY_GYM          (3 | (6 << 8))

// gMapGroup_Indoor_Pewter_City
#define MAP_PEWTERPOKECENTER (0 | (7 << 8))
#define MAP_PEWTER_POKE_MART (1 | (7 << 8))
#define MAP_PEWTER_CITY_GYM  (2 | (7 << 8))

// gMapGroup_Indoor_Mt_Moon
#define MAP_MT_MOON_POKE_CENTER (0 | (8 << 8))
#define MAP_MT_MOON_MART        (1 | (8 << 8))

// gMapGroup_Indoor_Cerulean_City
#define MAP_CERULEAN_POKEMON_CENTER (0 | (9 << 8))
#define MAP_CERULEAN_MART           (1 | (9 << 8))

// gMapGroup_Indoor_Vermillion_City
#define MAP_VERMILLION_POKE_CENTER (0 | (10 << 8))
#define MAP_VERMILLION_MART        (1 | (10 << 8))

// gMapGroup_Indoor_Lavender_Town
#define MAP_LAVENDER_TOWN_POKEMON_CENTER (0 | (11 << 8))
#define MAP_LAVENDER_MART                (1 | (11 << 8))

// gMapGroup_Indoor_Celadon_City
#define MAP_CELADON_POKE_CENTER (0 | (12 << 8))

// gMapGroup_Indoor_Saffron_City
#define MAP_SAFFRON_POKE_CENTER (0 | (13 << 8))
#define MAP_SAFFRON_MART        (1 | (13 << 8))

// gMapGroup_Indoor_Fuchsia_City
#define MAP_FUCHSIA_POKE_CENTER (0 | (14 << 8))
#define MAP_FUCHSIA_MART        (1 | (14 << 8))

// gMapGroup_Indoor_Cinnabar_Island
#define MAP_CINNABAR_POKE_CENTER (0 | (15 << 8))
#define MAP_CINNABAR_MART        (1 | (15 << 8))

// gMapGroup_Towns_Hoenn
#define MAP_PETALBURG_CITY   (0 | (16 << 8))
#define MAP_SLATEPORT_CITY   (1 | (16 << 8))
#define MAP_MAUVILLE_CITY    (2 | (16 << 8))
#define MAP_RUSTBORO_CITY    (3 | (16 << 8))
#define MAP_FORTREE_CITY     (4 | (16 << 8))
#define MAP_LILYCOVE_CITY    (5 | (16 << 8))
#define MAP_MOSSDEEP_CITY    (6 | (16 << 8))
#define MAP_SOOTOPOLIS_CITY  (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY (8 | (16 << 8))
#define MAP_LITTLEROOT_TOWN  (9 | (16 << 8))
#define MAP_OLDALE_TOWN      (10 | (16 << 8))
#define MAP_DEWFORD_TOWN     (11 | (16 << 8))
#define MAP_LAVARIDGE_TOWN   (12 | (16 << 8))
#define MAP_FALLARBOR_TOWN   (13 | (16 << 8))
#define MAP_VERDANTURF_TOWN  (14 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN  (15 | (16 << 8))

// gMapGroup_Routes_Hoenn
#define MAP_ROUTE101            (0 | (17 << 8))
#define MAP_ROUTE102            (1 | (17 << 8))
#define MAP_ROUTE103            (2 | (17 << 8))
#define MAP_ROUTE104            (3 | (17 << 8))
#define MAP_ROUTE105            (4 | (17 << 8))
#define MAP_ROUTE106            (5 | (17 << 8))
#define MAP_ROUTE107            (6 | (17 << 8))
#define MAP_ROUTE108            (7 | (17 << 8))
#define MAP_ROUTE109            (8 | (17 << 8))
#define MAP_ROUTE110            (9 | (17 << 8))
#define MAP_ROUTE111            (10 | (17 << 8))
#define MAP_ROUTE112            (11 | (17 << 8))
#define MAP_ROUTE113            (12 | (17 << 8))
#define MAP_ROUTE114            (13 | (17 << 8))
#define MAP_ROUTE115            (14 | (17 << 8))
#define MAP_ROUTE116            (15 | (17 << 8))
#define MAP_ROUTE117            (16 | (17 << 8))
#define MAP_ROUTE118            (17 | (17 << 8))
#define MAP_ROUTE119            (18 | (17 << 8))
#define MAP_ROUTE120            (19 | (17 << 8))
#define MAP_ROUTE121            (20 | (17 << 8))
#define MAP_ROUTE122            (21 | (17 << 8))
#define MAP_ROUTE123            (22 | (17 << 8))
#define MAP_ROUTE124            (23 | (17 << 8))
#define MAP_ROUTE125            (24 | (17 << 8))
#define MAP_ROUTE126            (25 | (17 << 8))
#define MAP_ROUTE127            (26 | (17 << 8))
#define MAP_ROUTE128            (27 | (17 << 8))
#define MAP_ROUTE129            (28 | (17 << 8))
#define MAP_ROUTE130            (29 | (17 << 8))
#define MAP_ROUTE131            (30 | (17 << 8))
#define MAP_ROUTE132            (31 | (17 << 8))
#define MAP_ROUTE133            (32 | (17 << 8))
#define MAP_ROUTE134            (33 | (17 << 8))
#define MAP_UNDERWATER_ROUTE124 (34 | (17 << 8))
#define MAP_UNDERWATER_ROUTE126 (35 | (17 << 8))
#define MAP_UNDERWATER_ROUTE127 (36 | (17 << 8))
#define MAP_UNDERWATER_ROUTE128 (37 | (17 << 8))
#define MAP_UNDERWATER_ROUTE129 (38 | (17 << 8))
#define MAP_UNDERWATER_ROUTE105 (39 | (17 << 8))
#define MAP_UNDERWATER_ROUTE125 (40 | (17 << 8))

// gMapGroup_Hoenn_Gyms
#define MAP_DEWFORD_TOWN_GYM        (0 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F   (1 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F  (2 | (18 << 8))
#define MAP_PETALBURG_CITY_GYM      (3 | (18 << 8))
#define MAP_MAUVILLE_CITY_GYM       (4 | (18 << 8))
#define MAP_RUSTBORO_CITY_GYM       (5 | (18 << 8))
#define MAP_FORTREE_CITY_GYM        (6 | (18 << 8))
#define MAP_MOSSDEEP_CITY_GYM       (7 | (18 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_1F  (8 | (18 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F (9 | (18 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (19 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (20 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (20 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (20 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (20 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (20 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (21 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (21 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (21 << 8))
#define MAP_DEWFORD_TOWN_HALL              (3 | (21 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (4 | (21 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (1 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (2 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (3 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (4 | (22 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (23 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (23 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (23 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (23 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (23 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (24 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (24 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (24 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (24 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (24 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (24 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (24 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (24 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (24 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (25 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (26 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (1 | (26 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (2 | (26 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (3 | (26 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (4 | (26 << 8))
#define MAP_PETALBURG_CITY_MART              (5 | (26 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (27 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (27 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (27 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (27 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (27 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (27 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (27 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (27 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (0 | (28 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (1 | (28 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (2 | (28 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (3 | (28 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (4 | (28 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (5 | (28 << 8))
#define MAP_MAUVILLE_CITY_MART              (6 | (28 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (29 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (29 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (3 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (4 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (5 | (29 << 8))
#define MAP_RUSTBORO_CITY_MART              (6 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (7 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (8 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (9 | (29 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (10 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (11 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (12 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (13 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (14 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (15 | (29 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (30 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (1 | (30 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (2 | (30 << 8))
#define MAP_FORTREE_CITY_MART              (3 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (4 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (5 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (6 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (7 | (30 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (8 | (30 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (31 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (31 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (31 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (31 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (31 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (31 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (31 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (31 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (31 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_HOUSE1            (0 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (1 | (32 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (2 | (32 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (3 | (32 << 8))
#define MAP_MOSSDEEP_CITY_MART              (4 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (5 | (32 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (6 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (7 | (32 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (8 | (32 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (9 | (32 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (10 | (32 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (11 | (32 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (0 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (1 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (2 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (3 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (4 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (5 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (6 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (7 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (8 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (9 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (10 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (11 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (12 | (33 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (34 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (35 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (35 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (36 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (36 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (37 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (37 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (38 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (38 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (38 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (39 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (40 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (41 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (42 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (42 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (42 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (42 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (42 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (42 << 8))
#define MAP_DESERT_RUINS                             (6 | (42 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (42 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (42 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (42 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (42 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (42 << 8))
#define MAP_MT_CHIMNEY                               (12 | (42 << 8))
#define MAP_JAGGED_PASS                              (13 | (42 << 8))
#define MAP_FIERY_PATH                               (14 | (42 << 8))
#define MAP_MT_PYRE_1F                               (15 | (42 << 8))
#define MAP_MT_PYRE_2F                               (16 | (42 << 8))
#define MAP_MT_PYRE_3F                               (17 | (42 << 8))
#define MAP_MT_PYRE_4F                               (18 | (42 << 8))
#define MAP_MT_PYRE_5F                               (19 | (42 << 8))
#define MAP_MT_PYRE_6F                               (20 | (42 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (42 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (42 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (42 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (42 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (42 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (42 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (42 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (42 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (42 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (42 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (42 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (42 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (42 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (42 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (42 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (42 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (42 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (42 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (42 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (42 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (42 << 8))
#define MAP_ISLAND_CAVE                              (67 | (42 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (42 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (42 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (42 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (42 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (42 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (42 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (42 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (42 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (42 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (42 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (42 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (42 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (42 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (42 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (42 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (42 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (42 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (42 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (42 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (42 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (42 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (42 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (42 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (42 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (42 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (42 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (42 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (42 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (42 << 8))
#define MAP_ALTERING_CAVE                            (106 | (42 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (42 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (43 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (43 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (43 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (43 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (43 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (43 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (43 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (43 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (43 << 8))
#define MAP_TRADE_CENTER             (25 | (43 << 8))
#define MAP_RECORD_CORNER            (26 | (43 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (43 << 8))
#define MAP_CONTEST_HALL             (28 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (43 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (43 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (43 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (43 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (43 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (43 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (43 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (43 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (43 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (43 << 8))
#define MAP_UNION_ROOM               (60 | (43 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (44 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (44 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (44 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (44 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (44 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (44 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (44 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (44 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (44 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (44 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (44 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (44 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (44 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (44 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (44 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (44 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (44 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (44 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (44 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (44 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (44 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (44 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (44 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (44 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (44 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (44 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (44 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (44 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (44 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (44 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (44 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (44 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (44 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (44 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (44 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (44 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (44 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (44 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (44 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (44 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (45 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (45 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (46 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (47 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (47 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (47 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (48 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (49 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (50 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (50 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (50 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (51 << 8))

#define MAP_GROUPS_COUNT 52

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
